### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by ken19950127** [pedropro/UrsoNet#1]
Hello, when I train the model, I get an error. Have you encountered it before?

Traceback (most recent call last):
  File "pose_estimator.py", line 878, in <module>
    model_dir=args.logs)
  File "/home/flyvideo/nan_file/cloth_keypoint_detect/UrsoNet/net.py", line 581, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/home/flyvideo/nan_file/cloth_keypoint_detect/UrsoNet/net.py", line 644, in build
    loc_pred = build_loc_graph(C6, config, nr_features)
  File "/home/flyvideo/nan_file/cloth_keypoint_detect/UrsoNet/net.py", line 300, in build_loc_graph
    x = KL.Reshape((nr_features,))(feature_map)
  File "/home/flyvideo/anaconda2/envs/py35/lib/python3.5/site-packages/keras/engine/topology.py", line 621, in __call__
    output_shape = self.compute_output_shape(input_shape)
  File "/home/flyvideo/anaconda2/envs/py35/lib/python3.5/site-packages/keras/layers/core.py", line 376, in compute_output_shape
    input_shape[1:], self.target_shape)
  File "/home/flyvideo/anaconda2/envs/py35/lib/python3.5/site-packages/keras/layers/core.py", line 364, in _fix_unknown_dimension
    original = np.prod(input_shape, dtype=int)
  File "/home/flyvideo/anaconda2/envs/py35/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2566, in prod
    out=out, **kwargs)
  File "/home/flyvideo/anaconda2/envs/py35/lib/python3.5/site-packages/numpy/core/_methods.py", line 35, in _prod
    return umr_prod(a, axis, dtype, out, keepdims)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by hhjjhhjjyyuuyyuu** [comment]
I get the same error. Have you solved it？

**Comment by Doublezore** [comment]
pip uninstall h5py
pip install h5py==2.10
